<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-NN51RLO" failures="1" tests="1" name="Test" time="0.096" errors="0" timestamp="2024-10-01T20:22:17 IST">
  <testcase classname="crawling.app.crawl.TestRunner" name="crawl" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2">
      <![CDATA[java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
at utils.csvReader.data(csvReader.java:39)
... 29 more
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- crawl -->
</testsuite> <!-- Test -->
